### ISSUE TITLE
What can I use this gem on?

### ISSUE THREAD

**Issue by PikachuEXE** [rg-3/xpool.rb#1]
I found this gem through [a Rubyflow Post](http://www.rubyflow.com/p/ontedq-xpoolrb-200-released)

It would be great to see some example use cases
i.e. Where and why do I want to use this gem

**Comment by rg-3** [comment]
Hey,

Thanks for the interest and sorry that I didn't see this issue sooner.
This gem is useful in scenarios where you want to run a background job, or run some task that should be handled asynchronously.

It could be used, for example, in a Sinatra application where you want to deliver an email asynchronously.

__app.rb__
```ruby
require 'sinatra'
require 'xpool'

class EmailJob
  def run(email)
    mail to: email, ...
  end
end

pool = XPool.new
get '/signup' do 
  # sign up logic
  pool.schedule EmailJob, params[:email]
end
```

Does that answer your question ? 

Thanks.

**Comment by rg-3** [comment]
Hey again,

I opened a pull request, #2 that mentions example scenarios.
Let me know if that helps.

Thanks.

**Comment by PikachuEXE** [comment]
Would be great if you include your `app.rb` example in README

Separate question: I am using rails with sidekiq
Do you think there is any reason I should use `xpool` for *some* tasks?

**Comment by rg-3** [comment]
Thanks for the feedback :)

I modified the examples to be closer to real world scenarios.

xpool.rb is not really intended for use inside Rails, but you could give it a try. xpool.rb is best suited for scripts or daemons that need an asynchronous way to schedule jobs without bringing in a dependency such as Redis.

**Comment by PikachuEXE** [comment]
> xpool.rb is not really intended for use inside Rails, but you could give it a try. xpool.rb is best suited for scripts or daemons that need an asynchronous way to schedule jobs without bringing in an external dependency (eg Redis).

Now having that on README would make the purpose of this gem much clearer

**Comment by rg-3** [comment]
Agreed, i will push that change.

**Comment by rg-3** [comment]
Alright, pushed that change a few moments ago.

**Comment by rg-3** [comment]
@PikachuEXE Can this issue be closed or can I provide you with more info ?

**Comment by PikachuEXE** [comment]
README looks much better now
Thanks for making these changes :)

**Comment by rg-3** [comment]
You're welcome.
